// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY2fqogUCIP1GwAstUbj8dX_LYWgn4Blg',
    appId: '1:1037599985090:web:d808448884ecc41a9a1a5b',
    messagingSenderId: '1037599985090',
    projectId: 'artify-ed407',
    authDomain: 'artify-ed407.firebaseapp.com',
    storageBucket: 'artify-ed407.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBORyFguUxaM2RdOJxZoIARaXC1BQnEwho',
    appId: '1:1037599985090:android:be01167fba3837ac9a1a5b',
    messagingSenderId: '1037599985090',
    projectId: 'artify-ed407',
    storageBucket: 'artify-ed407.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDROmnAQdl9yyK_EtI2R4lbFQzedpvhWb0',
    appId: '1:1037599985090:ios:5de0d8ad2f2978409a1a5b',
    messagingSenderId: '1037599985090',
    projectId: 'artify-ed407',
    storageBucket: 'artify-ed407.appspot.com',
    iosBundleId: 'com.example.artisty1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDROmnAQdl9yyK_EtI2R4lbFQzedpvhWb0',
    appId: '1:1037599985090:ios:5de0d8ad2f2978409a1a5b',
    messagingSenderId: '1037599985090',
    projectId: 'artify-ed407',
    storageBucket: 'artify-ed407.appspot.com',
    iosBundleId: 'com.example.artisty1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY2fqogUCIP1GwAstUbj8dX_LYWgn4Blg',
    appId: '1:1037599985090:web:7c624b7a0a71f21d9a1a5b',
    messagingSenderId: '1037599985090',
    projectId: 'artify-ed407',
    authDomain: 'artify-ed407.firebaseapp.com',
    storageBucket: 'artify-ed407.appspot.com',
  );
}
